### PR TITLE
Use new soroban-cli token create subcommand

### PR DESCRIPTION
**Pull request by paulbellamy**
Use the new `soroban-cli token create` subcommand from: https://github.com/stellar/soroban-cli/pull/166
This meant I had to update the xdr dependency, and some of the code using that.

### CODE REVIEW

**Comment by paulbellamy** [comment]
I think https://github.com/stellar/soroban-examples/pull/123 will fix the build here

**Comment by leighmcculloch** [comment]
@paulbellamy Now that soroban-examples is updated I've pushed the dep update in 304e48f and `make test` passes. I'm not sure how to tell the full scope of this PR so I'm going to leave it open for you to merge, but looks like it is good to go.

**Comment by leighmcculloch** [comment]
In 78cce35 I've pushed changes that remove the dependence on `soroban-token-contract`. Instead of using any utilities in that example crate, the project relies entirely on the `soroban-token-spec` for code that ships when deployed, and in tests it uses the simpler `Signature::Invoker` to authenticate as a source account.

I've change the way auth works for two reasons:
- It models the type of auth we'll actually be doing with the contract, via Freighter.
- It's the simpler form of auth that most developers will probably use because it is all they need.

**Comment by leighmcculloch** [comment]
@paulbellamy For any scripts that need to invoke the token contract, instead of using ed25519 keys/sigs, you can use the `--account` option:
Screen Shot 2022-10-04 at 12 15 40 AM

Last week I also updated the cli serve subcommand to support account, so this should all be good to go to support any use of accounts in this PR.

**Review by leighmcculloch — APPROVED** [review]

**Pull request merged**
