### PR TITLE
Update Frontend

### LINKED ISSUE #157: ODHack: Improve Frontend
### **Please add PRs to the [update-P21 branch](https://github.com/stellar/soroban-example-dapp/tree/update-P21)**
**Description:**
Enhance the frontend of the Soroban Example Dapp to improve user experience, visual appeal, and functionality.

**Tasks:**

- [ ] 1. **Redesign UI/UX : $150** 
   - Analyze the current user interface and user experience.
   - Propose and implement design improvements to make the Dapp more intuitive and visually appealing.
   - Ensure a consistent design language across all pages.

- [ ] 2. **Improve Responsiveness: $150** 
   - Ensure the Dapp is fully responsive and works seamlessly across different devices and screen sizes.
   - Test the Dapp on various browsers and devices to identify and fix any responsiveness issues.

**Expected Outcome:**
- A redesigned and visually appealing frontend for the Soroban Example Dapp.
- Improved responsiveness and performance across all devices and browsers.
- Smooth animations and transitions for a better user experience.
- A functional dark mode with a toggle switch.
- Improved form validation with clear and helpful error messages.

**Why This Is Important:**
Improving the frontend of the Soroban Example Dapp will significantly enhance the user experience, making the Dapp more accessible, responsive, and visually appealing. These enhancements will provide a better overall experience.

### PR DESCRIPTION
**Pull request by Ugo-X**
closes #157 

here is a media file to show what i have done. i just wanted to be sure i have approval

Screenshot 2024-08-04 at 14 49 10
Screenshot 2024-08-04 at 14 49 49

### CODE REVIEW

**Comment by Julian-dev28** [comment]
Hello @Ugo-X 

Thanks for all the efforts you've made so far in the last tasks to redesign the UI/UX and for enhancing responsiveness for the DApp.

After reviewing your submission, it was found that despite there being a lot of text and descriptions, the main objective of the tasks had not been met. The primary goal was to make the Dapp front end cooler by enhancing its visual appeal and intuitiveness.

By "cool," we mean a new sleek design that is compelling, standing out with the ability to engage users with a visually exciting Dapp. In that sense, we specifically refer to aspects such as a cohesive color scheme, intuitive navigation, animations that are really dynamic, and a fresh layout that is user-friendly. It is unfortunate that the current delivery lacks what the intended design improvements sought to create.

We were looking for a clear and tangible redesign aligned with these modern design principles, to qualify for the award and really bring the overall user experience to life.

If you need any further clarification or guidance on what's expected, please feel free to reach out. We appreciate your understanding and are looking forward to further contributions from you. 

Best regards,
Julian

**Comment by Ugo-X** [comment]
> Hello @Ugo-X
> 
> Thanks for all the efforts you've made so far in the last tasks to redesign the UI/UX and for enhancing responsiveness for the DApp.
> 
> After reviewing your submission, it was found that despite there being a lot of text and descriptions, the main objective of the tasks had not been met. The primary goal was to make the Dapp front end cooler by enhancing its visual appeal and intuitiveness.
> 
> By "cool," we mean a new sleek design that is compelling, standing out with the ability to engage users with a visually exciting Dapp. In that sense, we specifically refer to aspects such as a cohesive color scheme, intuitive navigation, animations that are really dynamic, and a fresh layout that is user-friendly. It is unfortunate that the current delivery lacks what the intended design improvements sought to create.
> 
> We were looking for a clear and tangible redesign aligned with these modern design principles, to qualify for the award and really bring the overall user experience to life.
> 
> If you need any further clarification or guidance on what's expected, please feel free to reach out. We appreciate your understanding and are looking forward to further contributions from you.
> 
> Best regards, Julian

Alright, this was not meant to be the design, just a mockup. Given all the details you just described I will be sure to reach out in the need of any further clarifications, and I will put out a PR before the week runs out. Thank you.

**Comment by Julian-dev28** [comment]
Great thanks!

**Comment by Julian-dev28** [comment]
Closing this one out!

Unfortunately this one does not meet the criteria for the bounty but regardless thanks again for the awesome work! I hope to see you at the next hackathon!

**Comment by Ugo-X** [comment]
https://www.figma.com/proto/JY2dP1yA8tRWLcf4Apavqf/Untitled?node-id=1-2&t=5nNkSMXgy3p52PvT-1&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1

**Pull request closed without merging**
