### PR TITLE
Implement NextJs and Github Actions Build Caching for the Dapp

### LINKED ISSUE #160: ODHack: Fix Node Workflow Build Issue
## Title: 

**Description:**
Resolve the build issue in the Node workflow where the `next build` command fails due to a type error in `contracts.ts` during a workflow check in the following pull request: https://github.com/stellar/soroban-example-dapp/pull/154

**Error Log:**
```
Failed to compile.

./shared/contracts.ts:8:25
Type error: Property 'testnet' does not exist on type '{ readonly futurenet: { readonly networkPassphrase: "Test SDF Future Network ; October 2022"; readonly contractId: "CAU23MVDEW7VMB3AXC5PL5GZO3HBYZPEIP2P46X4T3AIC4Y7FXYZWES5"; }; }'.

6 |
7 | export const abundance = new Abundance.Client({

8 | ...Abundance.networks.testnet,
| ^
9 | rpcUrl: rpcUrl,
10 | allowHttp: true,
11 |
Error: Process completed with exit code 1.
```

**Tasks:**
1. **Review Current Implementation:**
   - Review the `shared/contracts.ts` file to identify the source of the type error.
   - Verify the available networks in the `Abundance` client.

2. **Update Network Configuration:**
   - Correct the network configuration to use the appropriate network available in the `Abundance` client.
   - Ensure the `testnet` network configuration is correctly defined or replace it with an available network.

3. **Configure Build Caching:**
   - Configure build caching for Next.js to improve build times and provide faster rebuilds.
   - Follow the guidelines in the [Next.js documentation](https://nextjs.org/docs/messages/no-cache) for setting up build caching.

4. **Test the Build:**
   - Run `npm run build` to ensure the build completes successfully without errors.
   - Verify that the application runs correctly after the build.
   - Create a PR to test the workflow on Github

**Expected Outcome:**
- The type error in `shared/contracts.ts` is resolved.
- The build completes successfully without errors.
- The application runs correctly post-build.
- Improved build times with build caching configured.

**Why This Is Important:**
Fixing this build issue is crucial to ensure the continuous integration and deployment pipeline functions correctly, improving development efficiency and reliability.

### PR DESCRIPTION
**Pull request by kamalbuilds**
Fixes #160 

1. For Nextjs caching ,

next.config.js: I Configured Next.js to use webpack 5 and filesystem caching. This configuration ensures that Next.js can leverage caching for faster rebuilds.

2. Implementing GitHub Actions Build Caching: GitHub Actions supports caching to speed up workflows. We can cache the npm dependencies and any other build artifacts between workflow runs. 

So I Modified the workflow file (.github/workflows/nodejs.yml) to include caching steps.

This will optimize the workflow by reusing dependencies across workflow runs.

### Changes done are as follows

next.config.js: Configures Next.js to use webpack 5 and filesystem caching. This configuration ensures that Next.js can leverage caching for faster rebuilds.

GitHub Actions Workflow:

Caching: Utilizes GitHub Actions caching (actions/cache@v2) to cache npm dependencies (~/.npm) between workflow runs. This speeds up npm installs and builds.

next build: Uses npx next build instead of npm run build to trigger the Next.js build process directly. This ensures that Next.js caching mechanisms are utilized effectively.

By implementing these changes, you should see improvements in build performance due to optimized caching strategies both within Next.js and in your GitHub Actions workflow.

### CODE REVIEW

**Comment by Julian-dev28** [comment]
Screenshot 2024-07-16 at 5 57 37 PM
It looks like the build failed. Please see the attached screenshot

**Comment by kamalbuilds** [comment]
ok @Julian-dev28 taking a look at this

**Comment by kamalbuilds** [comment]
@Julian-dev28 please run the workflow

**Comment by Julian-dev28** [comment]
resolved by #170

**Pull request closed without merging**
